#!/bin/bash

set -e

echo "Building ytdwn..."
bun build index.ts --compile --target=bun-linux-arm64 --outfile ytdwn

echo "Deploying to pi@pi.local..."
scp ytdwn pi@pi.local:~
ssh pi@pi.local "sudo systemctl restart ytdwn"

rm ytdwn

echo "Done!"
